# Generated by Django 3.0.5 on 2020-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
