# Generated by Django 3.0.5 on 2020-05-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpostmodel_data_creazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmodel',
            name='data_creazione',
        ),
    ]
